apiVersion: v1
kind: Secret
metadata:
  name: loki-aws-creds
  namespace: logging
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ABC
  AWS_SECRET_ACCESS_KEY: DEF
---
# Source: loki-stack/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-grafana
  namespace: logging
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: loki
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "VXEyOHdDSlA0bldYT3ZJMVlGQmZac1NTWXZ0VTlDQ1QyS3NBZ3dzUw=="
  ldap-toml: ""
---
# Source: loki-stack/charts/loki/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
    release: loki
stringData:
  loki.yaml: |
    auth_enabled: false
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_write_timeout: 3m
      http_server_read_timeout: 3m
      grpc_server_max_recv_msg_size: 2147483648  # 2 GB
      grpc_server_max_send_msg_size: 2147483648
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 1073741824  # 1000 Mb
        max_send_msg_size: 1073741824
    ingester:
      chunk_block_size: 131072
      chunk_idle_period: 3m
      chunk_retain_period: 10m
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    querier:
      engine:
        timeout: 10m
      max_concurrent: 64
    common:
      path_prefix: /data/loki
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    query_scheduler:
      max_outstanding_requests_per_tenant: 8192
    
    query_range:
      align_queries_with_step: true
      max_retries: 2
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 500
            ttl: 12h
    chunk_store_config:
      max_look_back_period: 24h
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 2000
          ttl: 24h
    memberlist:
      join_members:
      - loki-memberlist
    schema_config:
      configs:
      - from: "2024-05-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          period: 24h
          prefix: index_
    storage_config:
      tsdb_shipper:
        active_index_directory: /data/loki/tsdb-index
        cache_location: /data/loki/tsdb-cache
      aws:
        bucketnames: grafana-loki-cluster-bucket-test
        region: eu-north-1
        s3forcepathstyle: true
        insecure: false
    compactor:
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      retention_enabled: true
      shared_store: s3
      compaction_interval: 10m
      working_directory: /data/loki/boltdb-shipper-compactor
    limits_config:
      retention_period: 240h
      max_query_parallelism: 16
      split_queries_by_interval: 10m
      ingestion_rate_mb: 500
      ingestion_burst_size_mb: 1000
      per_stream_rate_limit: "50M"
      per_stream_rate_limit_burst: "100M"
      max_concurrent_tail_requests: 50
      max_entries_limit_per_query: 500000
      max_global_streams_per_user: 2000000
      max_query_series: 50000
      max_streams_per_user: 1000000
---
# Source: loki-stack/charts/promtail/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-promtail
  namespace: logging
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki
stringData:
  promtail.yaml: |
    server:
      log_level: info
      log_format: logfmt
      http_listen_port: 3101


    clients:
      - url: http://loki:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
            regex: java-demo
            action: keep
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            regex: true/(.*)
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
            target_label: __path__



    limits_config:


    tracing:
      enabled: false
