apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-topology-aware
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
